### PR TITLE
Generalize power supply manager

### PR DESCRIPTION
**Pull request by urbpeti**
I made a cleaner and more general code for the problem.

### CODE REVIEW

**Comment by danielfromemarsys** [comment]
This change makes the code too complex, rendering the whole project unmaintainable.

**Review by gerhardberger — CHANGES_REQUESTED** [review]
This repository follows the clean coding principles and this change would change that for the worse, so in this form I cannot accept it.

Also, this limits the customisability of the software, because with this change only laptops are supported for charging.

Also, a person can have multiple devices, which is not supported in this case.

**Comment by urbpeti** [comment]
> This repository follows the clean coding principles and this change would change that for the worse, so in this form I cannot accept it.
```    switch {
        case *dani < *gellert && *dani < *gergo:
            fmt.Println("Dani laptopjat kell tolteni")
        case *gellert < *dani && *gellert < *gergo:
            fmt.Println("Gellert laptopjat kell tolteni")
        default:
            fmt.Println("Geri laptopjat kell tolteni")     
    }
```

> Also, this limits the customisability of the software, because with this change only laptops are supported for charging.

`    dani := flag.Int("dani", 100, "Dani` **laptopjanak** `toltottsegi szintje")`

> Also, a person can have multiple devices, which is not supported in this case.

I do not change the functionality and this was not supported before.

**Comment by gerhardberger** [comment]
Hi @urbpeti,

As far as I understand you are not able to co-operate with our standards, and this issue starts to became pointless.

The strings in the individual messages are currently the same but can be easily changed.

Also I cannot understand your motivation for this pull request as your name is not supported, and we are not willing to support charging your devices.

**Comment by urbpeti** [comment]
> Also I cannot understand your motivation for this pull request as your name is not supported, and we are not willing to support charging your devices.

This is not for me. It is for your usage. I think with these changes the code is more maintainable.

> The strings in the individual messages are currently the same but can be easily changed.

This remains true after the changes.

**Pull request closed without merging**
