### PR TITLE
Updates power.go, adds the possibility to charge Gergo's laptop

### PR DESCRIPTION
**Pull request by danielfromemarsys**
adds possibility to charge gergo's laptop

### CODE REVIEW

**Comment by danielfromemarsys** [comment]
Please merge it it's important to deploy this today.

**Review by gerhardberger — CHANGES_REQUESTED** [review]
I cannot see the tests for this use case. Please add them.

**Comment by danielfromemarsys** [comment]
Hi @gerhardberger, I tested all the additional code with the same coverage as the whole project was before. Also I copied the source to https://play.golang.org/ and it just ran fluently. Please merge it ASAP!!!!!

**Comment by gerhardberger** [comment]
LGTM 👍  ❤️

**Pull request merged**
